In [1]:
import torch 
X = torch.Tensor(2,3)
print(X)
# 2*3 Matrix에 난수를 넣어줌 

tensor([[ 0.0000e+00, -8.5899e+09,  0.0000e+00],
        [-8.5899e+09,  1.4569e-19,  6.4069e+02]])


In [2]:
X = torch.tensor([[1,2,3],[4,5,6]])
print(X)
# 2*3 Matrix에 지정된 값을 넣어줌 

tensor([[1, 2, 3],
        [4, 5, 6]])


In [3]:
x_tensor = torch.tensor(data=[2.0,3.0], requires_grad = True)
# requires_grad : 텐서에 대한 기울기를 저장할지 여부

In [4]:
import torch
x = torch.tensor(data=[2.0,3.0], requires_grad = True)
y = x**2
z = 2*y + 3

target = torch.tensor([3.0,4.0])
loss = torch.sum(torch.abs(z-target))
loss.backward()

print(x.grad, y.grad, z.grad)
# 

tensor([ 8., 12.]) None None


/Users/Moon/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:10: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the gradient for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations.
  # Remove the CWD from sys.path while we load stuff.


### 선형회귀분석 모델 
   - w, b를 업데이트하는 전체 과정 

In [6]:
import torch 
import torch.nn as nn
# torch.nn : 신경만 모델들이 포함 
import torch.optim as optim
# torch.optim : 경사하강법 알고리즘 
import torch.nn.init as init 
# torch.nn.init : 텐서에 초깃값을 주기 위해 필요한 함수 

In [10]:
num_data = 1000
num_epoch = 500

x = init.uniform_(torch.Tensor(num_data, 1), -10, 10)
# -10 ~ 10 사이의 값으로 [num_data, 1]이라는 텐서를 균등하게 초기화 
noise = init.normal_(torch.FloatTensor(num_data, 1), std = 1)
# 평균이 0 표준편차가 1인 값들을 넣어줌 
y = 2*x + 3
y_noise = y + noise 
# y_noise = y값에 noise를 더해서 실제 분석에서 사용하는 데이터와 유사하게 만듬 

In [13]:
print(x)

tensor([[ 9.7238],
        [ 8.6394],
        [ 8.9736],
        [-9.4964],
        [-3.9584],
        [-4.3171],
        [ 5.1522],
        [ 7.0093],
        [ 0.9810],
        [ 1.3620],
        [ 9.4590],
        [-2.5812],
        [-4.8709],
        [-4.4565],
        [ 6.3138],
        [-7.2174],
        [-2.0893],
        [ 1.7306],
        [ 0.0586],
        [ 1.3378],
        [-3.2687],
        [-3.5297],
        [-3.6831],
        [-9.7600],
        [-3.7252],
        [ 0.2202],
        [-0.2774],
        [-9.8891],
        [ 7.8862],
        [ 7.2290],
        [-1.6185],
        [-9.3400],
        [-5.3288],
        [-4.8075],
        [-6.5560],
        [ 0.5367],
        [ 0.1741],
        [-4.1527],
        [-1.2404],
        [ 2.7723],
        [-2.3194],
        [ 8.7346],
        [-3.0541],
        [-3.2427],
        [ 5.2496],
        [ 7.2720],
        [ 8.7057],
        [ 0.9341],
        [ 1.3358],
        [ 6.5715],
        [ 2.6885],
        [-7.6592],
        [ 9.

In [14]:
print(noise)

tensor([[ 8.2157e-01],
        [ 1.6273e+00],
        [-7.0633e-01],
        [-2.5208e+00],
        [-2.5490e-03],
        [-2.3757e+00],
        [-9.3201e-01],
        [ 5.6667e-01],
        [ 4.1197e-01],
        [ 8.4542e-01],
        [-1.0784e+00],
        [-3.3562e-01],
        [-9.6195e-01],
        [ 1.4495e+00],
        [ 3.2699e-01],
        [ 6.5802e-01],
        [ 1.1165e+00],
        [-1.1189e+00],
        [-1.4631e-01],
        [-1.8711e-01],
        [-1.4042e-01],
        [ 1.3752e+00],
        [-2.9525e-01],
        [-2.0017e-01],
        [ 3.4844e-01],
        [ 1.4246e+00],
        [ 2.3207e-01],
        [-7.6306e-02],
        [ 1.4709e-01],
        [-1.2554e+00],
        [ 1.2508e+00],
        [ 4.1478e-02],
        [-1.6368e+00],
        [-7.9435e-02],
        [-5.5250e-01],
        [-1.0813e+00],
        [ 5.6834e-01],
        [-2.5840e+00],
        [ 8.8379e-01],
        [-4.6020e-01],
        [-5.0964e-01],
        [ 1.8385e-01],
        [ 4.3388e-02],
        [-1

In [16]:
model = nn.Linear(1, 1)
# nn.Linear() : 선형회귀 모델을 만드는 함수 (특성의 수, 결과로 나오는 특성의 수, 편차 사용 여부)
# nn.Linear(1, 1) : x랑 y가 하나씩 있기때문에 이렇게 지정 
loss_func = nn.L1Loss()
# L1Loss : L1Loss손실을 뜻함 

In [18]:
optimizer = optim.SGD(model.parameters(), lr = 0.01)
# 최적화 함수라고도 하고 경사하강법을 적용하여 오차를 줄이고 최적의 가중치와 편차를 근사할 수 있음
# model.parameters()를 사용하여 선형회귀 모델의 변수 w와 b를 전달

In [19]:
label = y_noise 

for i in range(num_epoch):
    optimizer.zero_grad()
    # zero_grad : 각 반복 시 기울기를 0으로 초기화시켜주는 함수 
    # 기울기를 초기화해야 새로운 가중치와 편차에 대해서 새로운 기울기를 구할 수 있음 
    output = model(x)
    # output : model에 x를 넣어서 나온 결과 
    
    loss = loss_func(output, label)
    loss.backward()
    # loss.backward() : 각 변수, w와 b에 대한 기울기가 계산 
    optimizer.step()
    # optimizer.step() : 함수를 호출하여 model.parameters에서 리턴되는 변수들의 기울기에 학습률 0.01을 곱하여 빼줌으로 업데이트 
    
    if i % 10 == 0:
        print(loss.data)
        param_list = list(model.parameters())
        print(param_list[0].item(), param_list[1].item())

# 결과 : y = 2x + 3과 같이 w와 b가 2와 3에 근접한 것을 알 수 있다.

tensor(8.8991)
0.3353956341743469 -0.26561471819877625
tensor(6.5876)
0.8144366145133972 -0.2474547177553177
tensor(4.5441)
1.261560320854187 -0.21889473497867584
tensor(3.3598)
1.5816131830215454 -0.1647147387266159
tensor(3.0910)
1.7079956531524658 -0.08297473192214966
tensor(2.9803)
1.7571533918380737 0.008085275068879128
tensor(2.8848)
1.785241723060608 0.10146526992321014
tensor(2.7913)
1.8075919151306152 0.1955052763223648
tensor(2.6984)
1.8270068168640137 0.289905309677124
tensor(2.6061)
1.844054937362671 0.38440534472465515
tensor(2.5145)
1.8590762615203857 0.4789253771305084
tensor(2.4229)
1.8735231161117554 0.5735052227973938
tensor(2.3319)
1.887372612953186 0.6678251624107361
tensor(2.2416)
1.899215579032898 0.7621050477027893
tensor(2.1517)
1.9110053777694702 0.8561649918556213
tensor(2.0626)
1.9232510328292847 0.9497251510620117
tensor(1.9749)
1.9338858127593994 1.0426851511001587
tensor(1.8891)
1.9442477226257324 1.1347049474716187
tensor(1.8043)
1.9541966915130615 1.2261